sudo: required
dist: trusty

language: python
python:
  - "3.6"
install: 
  - sudo apt-get update
  - sudo apt-get install portaudio19-dev
  - pip install PyQt5 sip
  - pip install -r requirements.txt
  - bash tools/build_ui.sh
  - pip install nose
  - pip install coveralls
  - sudo apt-get install xvfb
  - sudo apt-get install libgl1-mesa-dri
  - Xvfb :99 &

script: DISPLAY=:99 nosetests -vv -l nose ./tests --with-coverage --cover-package=./anki
